-- lol
require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")

require("plugins.ranger")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.formatter")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.dashboard")
require("plugins.comments")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.bufferline")
require("plugins.luasnip")
require("plugins.colorizer")
